# 定义规则大类及其对应的上游数据源
TASKS = {
  "AI": [
    "OpenAI",
    "Claude",
    "Anthropic",
    "Gemini",
    "BardAI",
    "Copilot",
    "Civitai",
  ],
  "CnMax": [
    "AliPay", "JianGuoYun", "12306", "HeMa", "DingTalk", "Eleme", "CaiNiao", "MeiTuan", "WeChat", "CMB",
    "ICBC", "BOCOM", "BOC", "CCB", "CEB", "CGB", "ChinaTelecom", "ChinaUnicom", "ChinaMobile",
    "BiliBili", "Baidu", "Tencent", "QiNiuYun", "NetEaseMusic", "NetEase", "Hupu", "HuYa",
    "Douyu", "KuaiShou", "iQIYI", "TencentVideo", "Youku", "XiaoHongShu", "DouYin",

    "115", "12306", "17173", "178", "17zuoye",
    "360", "36kr", "3Type", "3dm", "4399",
    "4Paradigm", "51Job", "51nod", "56", "58TongCheng",
    "6JianFang", "8btc", "ABC", "AcFun", "Agora",
    "AiQiCha", "AirChina", "Ali213", "AliPay", "Alibaba",
    "AmazonCN", "AnTianKeJi", "Anjuke", "Antutu", "Apifox",
    "BOC", "BOCOM", "BaiDuTieBa", "BaiFenDian", "BaiShanYunKeJi",
    "Baidu", "BaoFengYingYin", "BeStore", "BesTV", "BianFeng",
    "BiliBili", "Bootcss", "ByteDance", "CAS", "CCB",
    "CCTV", "CEB", "CETV", "CGB", "CIBN",
    "CKJR", "CMB", "CNKI", "CNNIC", "CSDN",
    "CaiNiao", "CaiXinChuanMei", "Camera360", "ChengTongWangPan", "China",
    "ChinaASN", "ChinaIPs", "ChinaIPsBGP", "ChinaIPsTest", "ChinaMedia",
    "ChinaMobile", "ChinaNews", "ChinaNoMedia", "ChinaTelecom", "ChinaTest",
    "ChinaUnicom", "ChuangKeTie", "ChunYou", "Coolapk", "DaMai",
    "DanDanZan", "Dandanplay", "DangDang", "Dedao", "Deepin",
    "DiDi", "DiLianWangLuo", "DiSiFanShi", "DianCeWangKe", "DingTalk",
    "DingXiangYuan", "Domob", "DouBan", "DouYin", "Douyu",
    "DuoWan", "EastMoney", "Eleme", "FanFou", "FangZhengDianZi",
    "FeiZhu", "FengHuangWang", "FengXiaWangLuo", "Fiio", "Funshion",
    "GaoDe", "Geely", "Gitee", "GovCN", "GuiGuDongLi",
    "HaiNanHangKong", "HanYi", "HeMa", "HibyMusic", "Himalaya",
    "Hpplay", "HuYa", "HuaShuTV", "HuanJu", "Huawei",
    "HunanTV", "Hupu", "ICBC", "IPTVMainland", "JiGuangTuiSong",
    "JianGuoYun", "JianShu", "JinJiangWenXue", "JingDong", "JueJin",
    "Keep", "KingSmith", "Kingsoft", "KouDaiShiShang", "Ku6",
    "KuKeMusic", "KuaiDi100", "KuaiShou", "KuangShi", "KugouKuwo",
    "LanZouYun", "LeJu", "LeTV", "Lenovo", "LianMeng",
    "LuDaShi", "LvMiLianChuang", "MOOMusic", "Maocloud", "Marketing",
    "MeiTu", "MeiTuan", "MeiZu", "MiWu", "Migu",
    "MingLueZhaoHui", "Mogujie", "Mojitianqi", "NGA", "NGAA",
    "NetEase", "NetEaseMusic", "OPPO", "OnePlus", "OuPeng",
    "PPTV", "PSBC", "Picacg", "Pinduoduo", "PingAn",
    "QiNiuYun", "QingCloud", "Qyyjt", "RuanMei", "SFExpress",
    "SMG", "SMZDM", "ShangHaiJuXiao", "Shanling", "ShenMa",
    "ShiJiChaoXing", "ShiNongZhiKe", "Sina", "Sohu", "SouFang",
    "Stripe", "SuNing", "SuiShiChuanMei", "TCL", "TaiKang",
    "TaiheMusic", "TapTap", "Teambition", "Tencent", "TencentVideo",
    "TianTianKanKan", "TianWeiChengXin", "TianYaForum", "TigerFintech", "TongCheng",
    "U17", "UC", "UCloud", "UPYun", "UnionPay",
    "Vancl", "VipShop", "Vivo", "W3schools", "WanKaHuanJu",
    "WanMeiShiJie", "Wanfang", "WangSuKeJi", "WangXinKeJi", "WeChat",
    "WeType", "WeiZhiYunDong", "Weibo", "WenJuanXing", "WiFiMaster",
    "WoLai", "Wteam", "XiamiMusic", "XianYu", "XiaoGouKeJi",
    "XiaoMi", "XiaoYuanKeJi", "XieCheng", "XingKongWuXian", "XueErSi",
    "XueQiu", "Xunlei", "YYeTs", "YiChe", "YiXiaKeJi",
    "YiZhiBo", "YouMengChuangXiang", "YouZan", "Youku", "YuanFuDao",
    "YunFanJiaSu", "ZDNS", "ZhangYue", "ZhiYinManKe", "ZhiYunZhong",
    "Zhihu", "ZhongGuoShiHua", "ZhongWeiShiJi", "ZhongXingTongXun", "ZhongYuanYiShang",
    "ZhuanZhuan", "aiXcoder", "iFlytek", "iQIYI", "ifanr",
    "zhanqi"
  ]
}
