# 定义规则大类及其对应的上游数据源
TASKS = {
  "AI": [
    "OpenAI",
    "Claude",
    "Anthropic",
    "Gemini",
    "BardAI",
    "Copilot",
    "Civitai",
  ],
  "CnMax": [
    "AliPay", "JianGuoYun", "12306", "HeMa", "DingTalk", "Eleme", "CaiNiao", "MeiTuan", "WeChat", "CMB",
    "ICBC", "BOCOM", "BOC", "CCB", "CEB", "CGB", "ChinaTelecom", "ChinaUnicom", "ChinaMobile",
    "BiliBili", "Baidu", "Tencent", "QiNiuYun", "NetEaseMusic", "NetEase", "Hupu", "HuYa",
    "Douyu", "KuaiShou", "iQIYI", "TencentVideo", "Youku", "XiaoHongShu", "DouYin",

    "115", "12306", "17173", "178", "17zuoye",
    "360", "36kr", "3dm", "4399",
    "4Paradigm", "51Job", "51nod", "56", "58TongCheng",
    "6JianFang", "ABC", "AcFun", "Agora",
    "AiQiCha", "AirChina", "Ali213", "AliPay", "Alibaba",
    "AnTianKeJi", "Anjuke", "Antutu", "Apifox",
    "BOC", "BOCOM", "BaiDuTieBa", "BaiFenDian", "BaiShanYunKeJi",
    "Baidu", "BaoFengYingYin", "BeStore", "BesTV", "BianFeng",
    "BiliBili", "ByteDance", "CAS", "CCB",
    "CCTV", "CEB", "CETV", "CGB", "CIBN",
    "CKJR", "CMB", "CNKI", "CNNIC", "CSDN",
    "CaiNiao", "CaiXinChuanMei", "Camera360", "ChengTongWangPan",
    "ChinaMobile", "ChinaNews", "ChinaTelecom",
    "ChinaUnicom", "ChuangKeTie", "ChunYou", "Coolapk", "DaMai",
    "Dandanplay", "DangDang", "DiDi", "DiLianWangLuo", "DiSiFanShi",
    "DianCeWangKe", "DingTalk", "DingXiangYuan", "Domob", "DouBan",
    "DouYin", "Douyu", "DuoWan", "EastMoney", "Eleme", "FanFou",
    "FangZhengDianZi", "FeiZhu", "FengHuangWang", "FengXiaWangLuo",
    "Funshion", "GaoDe", "Geely", "Gitee", "GovCN", "HaiNanHangKong",
    "HanYi", "HeMa", "HibyMusic", "Himalaya", "Hpplay", "HuYa",
    "HuaShuTV", "Huawei", "HunanTV", "Hupu", "ICBC",
    "JiGuangTuiSong", "JianGuoYun", "JianShu", "JinJiangWenXue", "JingDong",
    "JueJin", "Keep", "Kingsoft", "KouDaiShiShang", "Ku6",
    "KuKeMusic", "KuaiDi100", "KuaiShou", "KuangShi", "KugouKuwo",
    "LanZouYun", "LeJu", "LeTV", "Lenovo", "LianMeng",
    "LuDaShi", "Marketing", "MeiTu", "MeiTuan", "MeiZu", "MiWu",
    "Migu", "Mogujie", "Mojitianqi", "NGA", "NGAA", "NetEase", "NetEaseMusic",
    "OPPO", "OnePlus", "PPTV", "PSBC", "Pinduoduo", "PingAn", "QiNiuYun",
    "QingCloud", "Qyyjt", "RuanMei", "SFExpress", "SMG", "SMZDM", "ShenMa",
    "ShiJiChaoXing", "Sina", "Sohu", "SouFang", "SuNing", "TaiKang",
    "TaiheMusic", "TapTap", "Teambition", "Tencent", "TencentVideo",
    "TianWeiChengXin", "TianYaForum", "TigerFintech", "TongCheng",
    "UC", "UPYun", "UnionPay", "Vancl", "VipShop", "Vivo", "W3schools",
    "WanMeiShiJie", "Wanfang", "WangSuKeJi", "WangXinKeJi", "WeChat",
    "WeType", "WeiZhiYunDong", "Weibo", "WenJuanXing", "WiFiMaster",
    "WoLai", "XiamiMusic", "XianYu", "XiaoMi", "XieCheng", "XueErSi",
    "Xunlei", "YYeTs", "YiChe", "YouMengChuangXiang", "YouZan", "Youku", "YuanFuDao",
    "ZDNS", "ZhangYue", "ZhiYinManKe", "Zhihu", "ZhongGuoShiHua", "ZhongWeiShiJi",
    "ZhongXingTongXun", "ZhongYuanYiShang", "ZhuanZhuan", "iFlytek", "iQIYI", "ifanr", "zhanqi"
  ]
}
